// model_config.h - Auto-generated by train_and_export.py
#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

#include <Arduino.h>

const int NUM_FEATURES = 6;
const int NUM_CLUSTERS = 3;
const float THRESHOLD = 3.45224476f;

const float MEANS[NUM_FEATURES] = {
    884.99501247f,
    3.22257483f,
    6.23631004f,
    2.36793371f,
    78.02393363f,
    78.80302973f
};

const float STDS[NUM_FEATURES] = {
    271.70399098f,
    1.01003968f,
    2.68135902f,
    1.08708267f,
    3.23158305f,
    5.96797165f
};

const float CENTROIDS[NUM_CLUSTERS][NUM_FEATURES] = {
    { -0.08958999f, -0.72259525f, -0.08405900f, 0.05067908f, -0.42176154f, 0.08615743f },
    { 0.09058258f, -0.02787293f, 0.03028296f, 0.00342466f, 1.90593701f, 0.09304234f },
    { 0.07471198f, 0.97722757f, 0.09712105f, -0.06926365f, -0.37904829f, -0.16083285f }
};

#endif // MODEL_CONFIG_H
