# train_and_export.py
"""Train an edge anomaly detection model and export ESP32 deployment artifacts."""

import argparse
import json
import os

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

DATA_FILES = ['engine_data.csv', 'engine_data_synthetic.csv']
FEATURE_COLS = [
    'Engine rpm',
    'Lub oil pressure',
    'Fuel pressure',
    'Coolant pressure',
    'lub oil temp',
    'Coolant temp'
]
DEFAULT_JSON = 'model_config.json'
DEFAULT_HEADER = 'model_config.h'
DEFAULT_ESP32_FOLDER = 'esp32_inference'


def parse_args():
    parser = argparse.ArgumentParser(
        description='Train K-Means on normal engine data and export ESP32 model artifacts.'
    )
    parser.add_argument('--data', help='Path to dataset CSV file')
    parser.add_argument('--output-json', default=DEFAULT_JSON, help='JSON config output file')
    parser.add_argument('--output-header', default=DEFAULT_HEADER, help='C++ header output file')
    parser.add_argument('--esp32-folder', default=DEFAULT_ESP32_FOLDER, help='ESP32 sketch folder for duplicate header copy')
    parser.add_argument('--clusters', type=int, default=3, help='Number of K-Means clusters')
    parser.add_argument('--threshold-percentile', type=float, default=95.0, help='Anomaly threshold percentile for normal data distances')
    return parser.parse_args()


def locate_dataset(data_file=None):
    if data_file:
        if os.path.exists(data_file):
            return data_file
        raise FileNotFoundError(f"Dataset file '{data_file}' not found.")

    for fname in DATA_FILES:
        if os.path.exists(fname):
            return fname
    raise FileNotFoundError(f"None of {DATA_FILES} exists in the project root.")


def load_dataframe(path):
    df = pd.read_csv(path)
    df.columns = [c.strip() for c in df.columns]
    missing_columns = [c for c in FEATURE_COLS + ['Engine Condition'] if c not in df.columns]
    if missing_columns:
        raise ValueError(f"Dataset is missing required columns: {missing_columns}")
    return df


def train_model(df, num_clusters, threshold_percentile):
    normal_df = df[df['Engine Condition'] == 0]
    if normal_df.empty:
        raise ValueError('No normal samples found in the dataset for training.')

    X = normal_df[FEATURE_COLS].values
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
    kmeans.fit(X_scaled)

    distances = kmeans.transform(X_scaled).min(axis=1)
    threshold = np.percentile(distances, threshold_percentile)

    config = {
        'feature_columns': FEATURE_COLS,
        'scaler_mean': scaler.mean_.tolist(),
        'scaler_std': scaler.scale_.tolist(),
        'centroids': kmeans.cluster_centers_.tolist(),
        'threshold': float(threshold),
        'threshold_percentile': float(threshold_percentile),
        'num_clusters': num_clusters,
        'num_features': len(FEATURE_COLS)
    }
    return config, len(df), len(normal_df)


def write_json(config, output_json):
    with open(output_json, 'w') as f:
        json.dump(config, f, indent=2)
    print(f"[OK] Saved {output_json}")


def write_header(config, output_header, esp32_folder):
    lines = [
        '// model_config.h - Auto-generated by train_and_export.py',
        '#ifndef MODEL_CONFIG_H',
        '#define MODEL_CONFIG_H',
        '',
        '#include <Arduino.h>',
        '',
        f'const int NUM_FEATURES = {config["num_features"]};',
        f'const int NUM_CLUSTERS = {config["num_clusters"]};',
        f'const float THRESHOLD = {config["threshold"]:.8f}f;',
        '',
        'const float MEANS[NUM_FEATURES] = {',
    ]

    for value in config['scaler_mean']:
        lines.append(f'    {value:.8f}f,')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};\n')

    lines.append('const float STDS[NUM_FEATURES] = {')
    for value in config['scaler_std']:
        lines.append(f'    {value:.8f}f,')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};\n')

    lines.append('const float CENTROIDS[NUM_CLUSTERS][NUM_FEATURES] = {')
    for centroid in config['centroids']:
        row = ', '.join(f'{val:.8f}f' for val in centroid)
        lines.append(f'    {{ {row} }},')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};\n')
    lines.append('#endif // MODEL_CONFIG_H')

    with open(output_header, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"[OK] Saved {output_header}")

    os.makedirs(esp32_folder, exist_ok=True)
    dest_header = os.path.join(esp32_folder, os.path.basename(output_header))
    with open(dest_header, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"[OK] Also wrote {dest_header}")


def main():
    args = parse_args()

    print('=' * 66)
    print('EDGE-AI OBD-II TRAIN & EXPORT')
    print('=' * 66)

    data_path = locate_dataset(args.data)
    df = load_dataframe(data_path)
    config, total_samples, normal_samples = train_model(
        df, args.clusters, args.threshold_percentile
    )

    print(f"[INFO] Using dataset: {data_path}")
    print(f"[INFO] Total rows: {total_samples}, Normal rows used for training: {normal_samples}")
    print(f"[INFO] K-Means clusters: {args.clusters}, threshold percentile: {args.threshold_percentile}")

    write_json(config, args.output_json)
    write_header(config, args.output_header, args.esp32_folder)

    print('\n[RESULT] Training complete.')
    print('Next steps:')
    print('  1) Open esp32_inference.ino in Arduino IDE')
    print('  2) Make sure esp32_inference/model_config.h is present')
    print('  3) Flash the ESP32 and run hil_player.py to stream serial data')


if __name__ == '__main__':
    main()
